dev:
  # used to store terraform state
  backend_bucket: "allied-world-cdktf-state-dev"
  vpc: "vpc-0d819d4ed2f6cf33f"
  subnets:
    - "subnet-05381beba1da37295"
    - "subnet-0e88f922959e7bb28"
  airflow:
    environments:
      - "data-engineering"
    peer_vpc: "vpc-0b18a53b9d7fa154a"
